/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "conversations.index": [],
    "conversations.store": [],
    "conversations.show": [
        {
            "name": "conversation",
            "required": true
        }
    ],
    "conversations.update": [
        {
            "name": "conversation",
            "required": true
        }
    ],
    "conversations.destroy": [
        {
            "name": "conversation",
            "required": true
        }
    ],
    "messages.index": [],
    "messages.store": [],
    "messages.show": [
        {
            "name": "message",
            "required": true
        }
    ],
    "messages.update": [
        {
            "name": "message",
            "required": true,
            "binding": "id"
        }
    ],
    "messages.destroy": [
        {
            "name": "message",
            "required": true
        }
    ],
    "chat_events.index": [],
    "chat_events.store": [],
    "chat_events.show": [
        {
            "name": "chat_event",
            "required": true
        }
    ],
    "chat_events.update": [
        {
            "name": "chat_event",
            "required": true
        }
    ],
    "chat_events.destroy": [
        {
            "name": "chat_event",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "app.dashboad": [],
    "app.businesses": [],
    "app.businesses.create": [],
    "app.businesses.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "login": [],
    "home": [],
    "customers.index": [],
    "customers.create": [],
    "customers.store": [],
    "customers.show": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.edit": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "customers.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "customer_services.index": [],
    "customer_services.store": [],
    "customer_services.show": [
        {
            "name": "customer_service",
            "required": true
        }
    ],
    "customer_services.update": [
        {
            "name": "customer_service",
            "required": true
        }
    ],
    "customer_services.destroy": [
        {
            "name": "customer_service",
            "required": true
        }
    ],
    "service_properties.index": [],
    "service_properties.store": [],
    "service_properties.show": [
        {
            "name": "service_property",
            "required": true
        }
    ],
    "service_properties.update": [
        {
            "name": "service_property",
            "required": true
        }
    ],
    "service_properties.destroy": [
        {
            "name": "service_property",
            "required": true
        }
    ],
    "customer_service_properties.index": [],
    "customer_service_properties.store": [],
    "customer_service_properties.show": [
        {
            "name": "customer_service_property",
            "required": true
        }
    ],
    "customer_service_properties.update": [
        {
            "name": "customer_service_property",
            "required": true
        }
    ],
    "customer_service_properties.destroy": [
        {
            "name": "customer_service_property",
            "required": true
        }
    ],
    "services.index": [],
    "services.store": [],
    "services.show": [
        {
            "name": "service",
            "required": true,
            "binding": "id"
        }
    ],
    "services.update": [
        {
            "name": "service",
            "required": true,
            "binding": "id"
        }
    ],
    "services.destroy": [
        {
            "name": "service",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.index": [],
    "payments.store": [],
    "payments.show": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.update": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.destroy": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "jobs.index": [],
    "jobs.store": [],
    "jobs.show": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "jobs.update": [
        {
            "name": "job",
            "required": true,
            "binding": "id"
        }
    ],
    "jobs.destroy": [
        {
            "name": "job",
            "required": true
        }
    ],
    "customer_properties.index": [],
    "customer_properties.store": [],
    "customer_properties.show": [
        {
            "name": "customer_property",
            "required": true
        }
    ],
    "customer_properties.update": [
        {
            "name": "customer_property",
            "required": true
        }
    ],
    "customer_properties.destroy": [
        {
            "name": "customer_property",
            "required": true
        }
    ],
    "medias.index": [],
    "medias.store": [],
    "medias.show": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "medias.update": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "medias.destroy": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "variations.index": [],
    "variations.store": [],
    "variations.show": [
        {
            "name": "variation",
            "required": true,
            "binding": "id"
        }
    ],
    "variations.update": [
        {
            "name": "variation",
            "required": true,
            "binding": "id"
        }
    ],
    "variations.destroy": [
        {
            "name": "variation",
            "required": true,
            "binding": "id"
        }
    ],
    "service_variations.index": [],
    "service_variations.store": [],
    "service_variations.show": [
        {
            "name": "service_variation",
            "required": true
        }
    ],
    "service_variations.update": [
        {
            "name": "service_variation",
            "required": true
        }
    ],
    "service_variations.destroy": [
        {
            "name": "service_variation",
            "required": true
        }
    ],
    "customer_service_variations.index": [],
    "customer_service_variations.store": [],
    "customer_service_variations.show": [
        {
            "name": "customer_service_variation",
            "required": true
        }
    ],
    "customer_service_variations.update": [
        {
            "name": "customer_service_variation",
            "required": true
        }
    ],
    "customer_service_variations.destroy": [
        {
            "name": "customer_service_variation",
            "required": true
        }
    ],
    "business.index": [],
    "business.store": [],
    "business.show": [
        {
            "name": "business",
            "required": true,
            "binding": "id"
        }
    ],
    "business.update": [
        {
            "name": "business",
            "required": true,
            "binding": "id"
        }
    ],
    "business.destroy": [
        {
            "name": "business",
            "required": true,
            "binding": "id"
        }
    ],
    "workers.index": [],
    "workers.store": [],
    "workers.show": [
        {
            "name": "worker",
            "required": true,
            "binding": "id"
        }
    ],
    "workers.update": [
        {
            "name": "worker",
            "required": true,
            "binding": "id"
        }
    ],
    "workers.destroy": [
        {
            "name": "worker",
            "required": true,
            "binding": "id"
        }
    ],
    "supports.index": [],
    "supports.store": [],
    "supports.show": [
        {
            "name": "support",
            "required": true,
            "binding": "id"
        }
    ],
    "supports.update": [
        {
            "name": "support",
            "required": true,
            "binding": "id"
        }
    ],
    "supports.destroy": [
        {
            "name": "support",
            "required": true,
            "binding": "id"
        }
    ]
}
}
export {};
